# frozen_string_literal: true

require 'test_helper'

# Tests for DeviseTokenAuth::Controllers::Helpers
#
# The Helpers module:
#  - Defines instance methods per mapping via .define_helpers (authenticate_X!,
#    X_signed_in?, current_X, X_session, render_authenticate_error)
#  - Defines group methods via .devise_token_auth_group (authenticate_G!,
#    G_signed_in?, current_G, current_Gs, set_group_user_by_token,
#    render_authenticate_error)
#  - Overrides ClassMethods#log_process_action to default status to 401

class DeviseTokenAuth::Controllers::HelpersTest < ActionDispatch::IntegrationTest
  include Warden::Test::Helpers

  # ------------------------------------------------------------------
  # describe_helpers: methods generated by define_helpers
  # These are exercised via /demo/members_only (DemoUserController, :user
  # mapping) and /demo/members_only_mang (DemoMangController, :mang mapping).
  # ------------------------------------------------------------------
  describe 'define_helpers – generated instance methods' do
    describe 'authenticate_user!' do
      describe 'when user is not authenticated' do
        before do
          get '/demo/members_only', params: {}, headers: {}
        end

        it 'returns 401' do
          assert_equal 401, response.status
        end

        it 'returns an unauthenticated error JSON body' do
          body = JSON.parse(response.body)
          assert_includes body['errors'], I18n.t('devise.failure.unauthenticated')
        end

        it 'does not return auth headers' do
          refute response.headers['access-token']
        end
      end

      describe 'when user is authenticated' do
        before do
          @resource = create(:user, :confirmed)
          @auth_headers = @resource.create_new_auth_token
          age_token(@resource, @auth_headers['client'])

          get '/demo/members_only', params: {}, headers: @auth_headers
        end

        it 'returns 200' do
          assert_equal 200, response.status
        end

        it 'returns a new access token' do
          assert response.headers['access-token'].present?
        end
      end
    end

    describe 'user_signed_in?' do
      describe 'when user is authenticated' do
        before do
          @resource = create(:user, :confirmed)
          @auth_headers = @resource.create_new_auth_token
          age_token(@resource, @auth_headers['client'])

          get '/demo/members_only', params: {}, headers: @auth_headers
        end

        it 'returns true' do
          assert @controller.user_signed_in?
        end
      end

      describe 'when user is not authenticated' do
        before do
          get '/demo/members_only', params: {}, headers: {}
        end

        it 'returns false' do
          refute @controller.user_signed_in?
        end
      end
    end

    describe 'current_user' do
      before do
        @resource = create(:user, :confirmed)
        @auth_headers = @resource.create_new_auth_token
        age_token(@resource, @auth_headers['client'])

        get '/demo/members_only', params: {}, headers: @auth_headers
      end

      it 'returns the authenticated user' do
        assert_equal @resource, @controller.current_user
      end

      it 'memoizes the result (same object on repeated calls)' do
        first  = @controller.current_user
        second = @controller.current_user
        assert_same first, second
      end
    end

    describe 'user_session' do
      describe 'when user is authenticated' do
        before do
          @resource = create(:user, :confirmed)
          @auth_headers = @resource.create_new_auth_token
          age_token(@resource, @auth_headers['client'])

          get '/demo/members_only', params: {}, headers: @auth_headers
        end

        it 'returns a non-nil session object' do
          assert_not_nil @controller.user_session
        end
      end

      describe 'when user is not authenticated' do
        before do
          get '/demo/members_only', params: {}, headers: {}
        end

        it 'returns nil' do
          assert_nil @controller.user_session
        end
      end
    end

    describe 'mang_signed_in? and current_mang – different mapping' do
      describe 'when mang is authenticated' do
        before do
          @mang = create(:mang_user, :confirmed)
          @auth_headers = @mang.create_new_auth_token
          age_token(@mang, @auth_headers['client'])

          get '/demo/members_only_mang', params: {}, headers: @auth_headers
        end

        it 'returns 200' do
          assert_equal 200, response.status
        end

        it 'mang_signed_in? returns true' do
          assert @controller.mang_signed_in?
        end

        it 'current_mang returns the authenticated mang' do
          assert_equal @mang, @controller.current_mang
        end

        it 'user_signed_in? returns false (different mapping)' do
          refute @controller.user_signed_in?
        end
      end
    end

    describe 'render_authenticate_error' do
      before do
        get '/demo/members_only', params: {}, headers: {}
      end

      it 'returns a JSON body with an errors key' do
        body = JSON.parse(response.body)
        assert body.key?('errors'), 'response body should have an "errors" key'
      end

      it 'errors array contains the unauthenticated message' do
        body = JSON.parse(response.body)
        assert_includes body['errors'], I18n.t('devise.failure.unauthenticated')
      end

      it 'sets Content-Type to application/json' do
        assert_match %r{application/json}, response.content_type
      end
    end
  end

  # ------------------------------------------------------------------
  # devise_token_auth_group – methods generated for a group mapping
  # Exercised via /demo/members_only_group (DemoGroupController, :member
  # group containing :user and :mang).
  # ------------------------------------------------------------------
  describe 'devise_token_auth_group – generated group methods' do
    describe 'authenticate_member!' do
      describe 'when no group member is authenticated' do
        before do
          get '/demo/members_only_group', params: {}, headers: {}
        end

        it 'returns 401' do
          assert_equal 401, response.status
        end

        it 'returns an unauthenticated error JSON body' do
          body = JSON.parse(response.body)
          assert_includes body['errors'], I18n.t('devise.failure.unauthenticated')
        end
      end

      describe 'when a user (first mapping) is authenticated' do
        before do
          @resource = create(:user, :confirmed)
          @auth_headers = @resource.create_new_auth_token
          age_token(@resource, @auth_headers['client'])

          get '/demo/members_only_group', params: {}, headers: @auth_headers
        end

        it 'returns 200' do
          assert_equal 200, response.status
        end
      end

      describe 'when a mang (second mapping) is authenticated' do
        before do
          @mang = create(:mang_user, :confirmed)
          @auth_headers = @mang.create_new_auth_token
          age_token(@mang, @auth_headers['client'])

          get '/demo/members_only_group', params: {}, headers: @auth_headers
        end

        it 'returns 200' do
          assert_equal 200, response.status
        end
      end
    end

    describe 'member_signed_in?' do
      describe 'when user is authenticated' do
        before do
          @resource = create(:user, :confirmed)
          @auth_headers = @resource.create_new_auth_token
          age_token(@resource, @auth_headers['client'])

          get '/demo/members_only_group', params: {}, headers: @auth_headers
        end

        it 'returns true' do
          assert @controller.member_signed_in?
        end
      end

      describe 'when mang is authenticated' do
        before do
          @mang = create(:mang_user, :confirmed)
          @auth_headers = @mang.create_new_auth_token
          age_token(@mang, @auth_headers['client'])

          get '/demo/members_only_group', params: {}, headers: @auth_headers
        end

        it 'returns true' do
          assert @controller.member_signed_in?
        end
      end

      describe 'when no one is authenticated' do
        before do
          get '/demo/members_only_group', params: {}, headers: {}
        end

        it 'returns false' do
          refute @controller.member_signed_in?
        end
      end
    end

    describe 'current_member' do
      describe 'when user is authenticated' do
        before do
          @resource = create(:user, :confirmed)
          @auth_headers = @resource.create_new_auth_token
          age_token(@resource, @auth_headers['client'])

          get '/demo/members_only_group', params: {}, headers: @auth_headers
        end

        it 'returns the authenticated user as current member' do
          assert_equal @resource, @controller.current_member
        end

        it 'memoizes the result' do
          first  = @controller.current_member
          second = @controller.current_member
          assert_same first, second
        end
      end

      describe 'when mang is authenticated' do
        before do
          @mang = create(:mang_user, :confirmed)
          @auth_headers = @mang.create_new_auth_token
          age_token(@mang, @auth_headers['client'])

          get '/demo/members_only_group', params: {}, headers: @auth_headers
        end

        it 'returns the authenticated mang as current member' do
          assert_equal @mang, @controller.current_member
        end
      end
    end

    describe 'current_members' do
      describe 'when user is authenticated' do
        before do
          @resource = create(:user, :confirmed)
          @auth_headers = @resource.create_new_auth_token
          age_token(@resource, @auth_headers['client'])

          get '/demo/members_only_group', params: {}, headers: @auth_headers
        end

        it 'includes the authenticated user' do
          assert_includes @controller.current_members, @resource
        end

        it 'does not include unauthenticated users' do
          other = create(:user, :confirmed)
          refute_includes @controller.current_members, other
        end
      end

      describe 'when mang is authenticated' do
        before do
          @mang = create(:mang_user, :confirmed)
          @auth_headers = @mang.create_new_auth_token
          age_token(@mang, @auth_headers['client'])

          get '/demo/members_only_group', params: {}, headers: @auth_headers
        end

        it 'includes the authenticated mang' do
          assert_includes @controller.current_members, @mang
        end
      end

      describe 'when no one is authenticated' do
        before do
          get '/demo/members_only_group', params: {}, headers: {}
        end

        it 'returns an empty array' do
          assert_empty @controller.current_members
        end
      end
    end

    describe 'render_authenticate_error (group)' do
      before do
        get '/demo/members_only_group', params: {}, headers: {}
      end

      it 'returns 401 status' do
        assert_equal 401, response.status
      end

      it 'returns a JSON body with an errors key containing unauthenticated message' do
        body = JSON.parse(response.body)
        assert_includes body['errors'], I18n.t('devise.failure.unauthenticated')
      end
    end
  end

  # ------------------------------------------------------------------
  # log_process_action – ClassMethods override
  # Sets payload[:status] to 401 when no status is present and no
  # exception is raised.
  # ------------------------------------------------------------------
  describe 'ClassMethods#log_process_action' do
    let(:controller_class) { DemoUserController }

    it 'sets status to 401 when payload has no status and no exception' do
      payload = {}
      controller_class.log_process_action(payload)
      assert_equal 401, payload[:status]
    end

    it 'preserves an existing status in the payload' do
      payload = { status: 200 }
      controller_class.log_process_action(payload)
      assert_equal 200, payload[:status]
    end

    it 'does not set status when an exception is present' do
      payload = { exception: ['RuntimeError', 'boom'] }
      controller_class.log_process_action(payload)
      refute payload.key?(:status), 'status should not be set when an exception is present'
    end

    it 'is defined on the controller class' do
      assert controller_class.respond_to?(:log_process_action)
    end
  end
end
