# frozen_string_literal: true

class DeviseTokenAuthCreateMultiEmailUserEmails < ActiveRecord::Migration[7.0]
  def change
    create_table(:multi_email_user_emails) do |t|
      t.references :multi_email_user, null: false, foreign_key: true, type: :bigint
      t.string  :email,   null: false
      # devise-multi_email gem requires a column named `primary` (boolean).
      # The gem calls `email_record.primary?` and `email_record.primary = value`
      # which are auto-generated by ActiveRecord from this column name.
      t.boolean :primary, null: false, default: false

      # Confirmable columns — required by :multi_email_confirmable which
      # includes devise :confirmable into each email record.
      t.string   :confirmation_token
      t.datetime :confirmed_at
      t.datetime :confirmation_sent_at
      t.string   :unconfirmed_email

      t.timestamps
    end

    add_index :multi_email_user_emails, :email,     unique: true
    add_index :multi_email_user_emails, :confirmation_token,
              name: 'index_multi_email_user_emails_on_confirmation_token', unique: true
    add_index :multi_email_user_emails, [:multi_email_user_id, :primary],
              name: 'index_multi_email_user_emails_on_user_and_primary'
  end
end
